# Reference https://github.com/emotion-js/emotion/blob/master/.circleci/config.yml
version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v4-dependencies-
      - run: yarn install --pure-lockfile
      - run:
          name: Ava Tests
          command: yarn test
  release:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Git setup
          command: |
            git config user.email "circleci-bot@circleci.com"
            git config user.name "Release Bot 🤖"
            git remote set-url origin https://${GITHUB_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git
      - run:
          name: Release checking
          command: |
            LATEST_COMMIT=$(git log --oneline -n 1 HEAD)
            COMMIT_REGEX="(develop|staging|release|ci:)"

            if [[ $LATEST_COMMIT =~ $COMMIT_REGEX ]]; then
                echo "This is a release, kill this one!"
                circleci step halt
            else
              echo "Proceed. Prepare a new release"
            fi

      - run:
          name: NPM setup
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v4-dependencies-
      - run: yarn install --pure-lockfile
      - run:
          name: Add changelog and stuff
          command: npx standard-version -a
      - run:
          name: Add git tags and releseases
          command: git push --follow-tags origin master
      - run:
          name: Publish to NPM through Yarn
          command: |
            PACKAGE_VERSION=$(cat package.json | grep \\\"version\\\" | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]') && yarn publish --new-version $PACKAGE_VERSION

workflows:
  version: 2
  test-and-publish:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only: master
