version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:14.5

commands:
  getcommitmsg:
    steps:
      - run:
          name: Get commit message
          command: |
            echo 'export GIT_COMMIT_MSG=$(git log -1 --pretty=format:"%s")' >> $BASH_ENV
            source $BASH_ENV
  setup:
    steps:
      - checkout
      - run:
          name: Install js dependencies
          command: yarn install

  setupgit:
    steps:
      - run:
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "releasebot@vorillaz.com"
            git config user.name "Vostok Release Bot"
            git remote set-url origin https://${GITHUB_TOKEN}@github.com/${CIRCLE_PROJECT_REPONAME}.git
            git checkout master

  setupci:
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
jobs:
  tests:
    executor: node
    steps:
      - setupci
      - run:
          name: Run tests
          command: yarn test

  release:
    executor: node
    steps:
      - setupgit
      - getcommitmsg
      - setup
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Release
          command: |
            RELEASE_REGEX="(release|no-release)";
            if [[ $GIT_COMMIT_MSG !~ $RELEASE_REGEX ]]; then
              yarn release;
            else
                echo "Released: ";
                echo $GIT_COMMIT_MSG;
            fi
workflows:
  version: 2
  pipeline:
    jobs:
      - tests:
          filters:
            branches:
              ignore: master
      - release:
          filters:
            branches:
              only: master
