name: Release
on:
  push:
    branches:
      - main
      - next
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: NPM setup
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Setup bot
        run: |
          git config user.email "github-bot@proxima.so"
          git config user.name "Vostok Release Bot 🤖"

      - name: Install Dependencies
        run: npm ci

      - name: Add changelog and stuff
        run: npx standard-version -a

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Release checking
        run: |
          LATEST_COMMIT=$(git log --oneline -n 1 HEAD)
          COMMIT_REGEX="(develop|staging|release|ci)"
          if [[ $LATEST_COMMIT =~ $COMMIT_REGEX ]]; then
              echo "This is a release or maintainance, kill this one!"
              exit 1
          else
            echo "Proceed. Prepare a new release"
          fi

      - name: Publish to NPM
        run: npm publish

      - name: Add git tags, releases and push
        run: |
          git add .
          git commit --amend --no-edit -n
          git push --follow-tags origin master
